### ISSUE TITLE
Idea: Make translation dynamic

### ISSUE THREAD

**Issue by Heonozis** [IvanTatarenko/resume#1]
You have your different language pages as different files, so each time you need to make changes on your page you do it twice.

I think better approach will be having one page with dynamic language content inside.

Fox example: you can create several translations and run them on same html page without need of duplicate work every time!

Take a look at this example of usage `i18n.js` 
https://phrase.com/blog/posts/step-step-guide-javascript-localization/

**Comment by IvanTatarenko** [comment]
Done, thanks for the help.
